# Generated by Django 4.1.3 on 2022-12-03 15:28

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_article_id_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_quill.fields.QuillField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=124),
        ),
    ]
