# Generated by Django 4.1.3 on 2022-12-03 16:24

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_article_body_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
